# Separate demo build: copies are derived at build time; instrumented sources remain intact.
option(XR64_CALL_FAULT_JOURNAL "Record exact indirect caller and loaded target provenance for crash localization" OFF)
option(XR64_FAULT_FRAME_CAPTURE "Private opt-in frame snapshots for runtime fault localization" OFF)
option(XR64_RW_REPLAY_DIAGNOSTICS "Private bounded replay arm and guest input delivery evidence" OFF)
function(xr64_demo_sources target)
    get_target_property(original_sources ${target} SOURCES)
    get_target_property(original_dir ${target} SOURCE_DIR)
    set(consumer_release_args)
    if(XR64_PUBLIC_RELEASE)
        list(APPEND consumer_release_args --consumer-release)
    endif()
    set(audio_hook_args)
    if(XR64_AUDIO)
        list(APPEND audio_hook_args --audio-producer-hook)
    endif()
    if(XR64_FAULT_FRAME_CAPTURE AND target STREQUAL "rage_wars_pc")
        target_compile_definitions(${target} PRIVATE XR64_FAULT_FRAME_CAPTURE=1)
    endif()
    if(XR64_RW_REPLAY_DIAGNOSTICS AND target STREQUAL "rage_wars_pc")
        target_compile_definitions(${target} PRIVATE XR64_RW_REPLAY_DIAGNOSTICS=1)
    endif()
    set(journal_args)
    set(journal_dependencies)
    if(XR64_CALL_FAULT_JOURNAL)
        if(MSVC AND target STREQUAL "rage_wars_pc")
            # Guest scheduler exceptions can cross the C callback ABI; the
            # diagnostic invocation guard must observe their unwind.
            target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:/EHc->)
        endif()
        set(journal_table "${RAGE_WARS_REPO_ROOT}/staging/rage-wars-recomp-spike/generated/ares_boot_to_combat/recomp_overlays.inl")
        list(APPEND journal_args --call-journal --call-journal-table "${journal_table}")
        list(APPEND journal_dependencies "${RAGE_WARS_REPO_ROOT}/scripts/prepare_call_journal.py" "${journal_table}")
    endif()
    set(demo_sources)
    set(generated_sources)
    foreach(source IN LISTS original_sources)
        if(source MATCHES "^\\$<" OR NOT source MATCHES "\\.(c|cpp|cc)$")
            list(APPEND demo_sources "${source}")
            continue()
        endif()
        get_filename_component(absolute "${source}" ABSOLUTE BASE_DIR "${original_dir}")
        file(RELATIVE_PATH relative "${RAGE_WARS_REPO_ROOT}" "${absolute}")
        if(relative MATCHES "^\\.\\.")
            message(FATAL_ERROR "Demo source outside repository: ${absolute}")
        endif()
        string(SHA256 source_id "${relative}")
        string(SUBSTRING "${source_id}" 0 12 source_id)
        get_filename_component(leaf "${absolute}" NAME)
        set(output "${CMAKE_CURRENT_BINARY_DIR}/demo-sources/${target}/${source_id}_${leaf}")
        add_custom_command(OUTPUT "${output}"
            COMMAND "${Python3_EXECUTABLE}" "${RAGE_WARS_REPO_ROOT}/scripts/prepare_demo_source.py"
                --input "${absolute}" --output "${output}" ${audio_hook_args} ${journal_args} ${consumer_release_args}
            DEPENDS "${absolute}" "${RAGE_WARS_REPO_ROOT}/scripts/prepare_demo_source.py" ${journal_dependencies}
            VERBATIM)
        get_filename_component(parent "${absolute}" DIRECTORY)
        set_source_files_properties("${output}" TARGET_DIRECTORY ${target} PROPERTIES GENERATED TRUE INCLUDE_DIRECTORIES "${parent}")
        list(APPEND generated_sources "${output}")
        list(APPEND demo_sources "${output}")
    endforeach()
    add_custom_target(${target}_demo_sources DEPENDS ${generated_sources})
    add_dependencies(${target} ${target}_demo_sources)
    set_property(TARGET ${target} PROPERTY SOURCES "${demo_sources}")
    target_compile_definitions(${target} PRIVATE XR64_DEMO_BUILD=1)
endfunction()
