[input]
entrypoint = 0x80000400
symbols_file_path = "../symbols/rage_wars.us.ares_boot_to_combat.toml"
rom_file_path = "../input/rage_wars.us.v1.0.z64"
output_func_path = "../generated/ares_boot_to_combat"
functions_per_output_file = 50

[patches]
hook = [
    { func = "recomp_entrypoint", before_vram = 0x80000484, text = "extern int xr64_rw076_duplicate_entrypoint_break(void);\nif (xr64_rw076_duplicate_entrypoint_break()) {\n    return;\n}" },
]
ignored = [
    'resident_wave9_func_002B9BE0',
    "virtual_wave14_func_00444260",
    "resident_wave14_external_0025E1B4",
    "resident_wave14_external_002A55B0",
    "resident_wave9_func_002B9DA8",
    "resident_wave9_func_002B9EAC",
    "gate4_func_002AD2A0",
    "gate4_func_002B9CA0",
    "func_002BAD70",
    "func_002BCE60",
    "func_002BCE80",
    "gate5_shared_002BC29C",
    "gate5_shared_002BC4A0",
    "gate7_host_002AD320",
    "gate7_func_002BACA0",
    "resident_wave11_func_0023C76C",
    "gate7_host_002BCE30",
    "gate7_host_002BCFB0",
    "gate7_host_002BD0A0",
    "gate7_host_002BD220",
    "resident_wave11_func_002BACD0",
    "resident_wave11_func_002BA280",
    "resident_wave14_func_002BA580",
    "resident_wave11_func_002B7210",
    "resident_wave9_func_002B71F0",
    "resident_wave9_host_002BCEA0",
    "resident_wave11_host_002BD160",
    "gate4_func_002BABC0",
    "gate4_func_002BB680",
    "resident_wave14_func_002B9970",
    "resident_wave11_func_002BB480",
    "resident_wave9_func_002BAB90",
    "resident_wave11_func_002BB090",
    "gate7_func_002BB1D0",
    "gate7_func_002BB350",
    "resident_wave15_external_00256E48",
    "resident_wave15_external_002B2400",
    "resident_wave9_func_002BB520",
    "resident_wave14_func_00411E4C",
    "resident_wave14_external_004009F4",
    "resident_wave14_external_0040184C",
    "resident_wave14_external_00401980",
    "resident_wave14_external_004030E0",
    "resident_wave14_external_00403458",
    "resident_wave14_external_004037D4",
    "resident_wave14_external_004037E8",
    "resident_wave14_external_00404D84",
    "resident_wave14_external_0040C11C",
    "resident_wave14_external_0040E9A8",
    "resident_wave14_external_0040ECB0",
    "resident_wave14_external_0040F5B4",
    "resident_wave14_external_0041174C",
    "resident_wave14_external_00411E70",
    "resident_wave14_external_00411E98",
    "resident_wave14_external_00411F6C",
    "resident_wave14_external_004143E0",
    "resident_wave14_external_00414430",
    "resident_wave14_external_00414D4C",
    "resident_wave14_external_0041991C",
    "resident_wave14_external_00419EA4",
    "resident_wave14_external_0041A480",
    "resident_wave14_external_0041A5D0",
    "resident_wave14_external_0041AC10",
    "resident_wave14_external_0041B160",
    "resident_wave14_external_0041B660",
    "resident_wave14_external_0041EAE0",
    "resident_wave14_external_0041F1B0",
    "resident_wave15_external_00441384",
    "resident_wave15_external_002097E8",
    "resident_wave15_external_0021A78C",
    "resident_wave15_external_0022692C",
    "resident_wave15_external_002A6E98",
    "resident_wave15_external_00449064",
    "resident_wave14_external_00442B98",
    "resident_wave14_external_00446EF0",
    "resident_wave15_external_00220A5C",
    "resident_wave15_external_00264B1C",
    "resident_wave15_external_00264B2C",
    "resident_wave15_external_00449358",
    "resident_wave14_external_0044A1EC",
    "resident_wave14_external_0044AFE0",
    "resident_wave15_external_002AD870",
    "resident_wave14_external_0044C100",
    "resident_wave14_external_0044D904",
    "resident_wave14_external_0044E1D0",
    "resident_wave15_external_00448E90",
    
    "trace_func_0042D190_r0022DD90",
    
    "trace_func_002BD080_r000BDC80",
]
instruction = [
    { func = "recomp_entrypoint", vram = 0x8000040C, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x80000410, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x80000418, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x8000041C, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x80000420, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x80000428, value = 0x00000000 },
    { func = "recomp_entrypoint", vram = 0x8000043C, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004A0, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004A4, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004A8, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004AC, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004C4, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004C8, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004D0, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004DC, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004E0, value = 0x00000000 },
    { func = "STVM_MapTLB", vram = 0x800004F4, value = 0x00000000 },
    { func = "func_002BCF40", vram = 0x002BCF6C, value = 0x00000000 },
    { func = "func_002BCF40", vram = 0x002BCF90, value = 0x00000000 },
    { func = "func_002BD1B0", vram = 0x002BD1DC, value = 0x00000000 },
    { func = "func_002BD1B0", vram = 0x002BD200, value = 0x00000000 },
]
