#!/usr/bin/env python3
"""Create or verify the immutable generated-source manifest for Rage Wars."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


def source_names(generated_dir: Path) -> list[str]:
    names = sorted(
        path.name
        for path in generated_dir.iterdir()
        if path.is_file() and path.suffix in {".c", ".cpp"}
    )
    invalid = [
        name for name in names
        if name != "lookup.cpp" and not (name.startswith("funcs_") and name.endswith(".c"))
    ]
    if invalid:
        raise RuntimeError(f"unexpected generated translation units: {', '.join(invalid)}")
    if "lookup.cpp" not in names:
        raise RuntimeError("generated lookup.cpp is missing")
    if not any(name.startswith("funcs_") for name in names):
        raise RuntimeError("no generated funcs_*.c translation units found")
    return names


def payload(generated_dir: Path, names: list[str]) -> dict[str, object]:
    encoded = "\n".join(names).encode("utf-8")
    return {
        "schema": "xr64.rage-wars.generated-source-manifest.v1",
        "generated_dir": generated_dir.resolve().as_posix(),
        "sources": names,
        "source_count": len(names),
        "source_list_sha256": hashlib.sha256(encoded).hexdigest(),
    }


def write_cmake(output: Path, data: dict[str, object]) -> None:
    lines = [
        "# Generated by tools/build_generated_source_manifest.py. Do not hand-edit.",
        f"set(RAGE_WARS_GENERATED_SOURCE_COUNT {data['source_count']})",
        f"set(RAGE_WARS_GENERATED_SOURCE_LIST_SHA256 \"{data['source_list_sha256']}\")",
        "set(RAGE_WARS_GENERATED_SOURCES",
    ]
    generated_dir = Path(str(data["generated_dir"]))
    lines.extend(f"    \"{(generated_dir / name).as_posix()}\"" for name in data["sources"])
    lines.append(")\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated-dir", required=True, type=Path)
    parser.add_argument("--cmake-output", required=True, type=Path)
    parser.add_argument("--json-output", required=True, type=Path)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    generated_dir = args.generated_dir.resolve()
    if not generated_dir.is_dir():
        raise RuntimeError(f"generated directory is missing: {generated_dir}")
    current = payload(generated_dir, source_names(generated_dir))

    if args.verify:
        if not args.json_output.is_file():
            raise RuntimeError("generated manifest is missing; run without --verify once")
        recorded = json.loads(args.json_output.read_text(encoding="utf-8"))
        # Verify immutable inventory, then generate paths for this checkout.
        for field in ("schema", "sources", "source_count", "source_list_sha256"):
            if recorded.get(field) != current[field]:
                raise RuntimeError(
                    "generated translation-unit inventory changed; regenerate and review the manifest")
        write_cmake(args.cmake_output, current)
        return 0

    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(current, indent=2) + "\n", encoding="utf-8")
    write_cmake(args.cmake_output, current)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)
