from pathlib import Path
r=Path(__file__).resolve().parents[1]
import hashlib, argparse
parser=argparse.ArgumentParser()
parser.add_argument('--rom',type=Path,default=r/'staging/rage-wars-recomp-spike/input/rage_wars.us.v1.0.z64')
parser.add_argument('--generation-only',action='store_true')
args=parser.parse_args()
rom=args.rom.read_bytes()
assert hashlib.sha256(rom).hexdigest()=='0433043aaba2649bdd1fe717c4020550ac663c0362527aa082490f5977a3e46b'
p=r/'staging/rage-wars-recomp-spike/generated/ares_boot_to_combat/funcs_34.c';s=p.read_text();a=s.index('RECOMP_FUNC void trace_func_002ABB0C_r000AC70C(');b=s.find('RECOMP_FUNC void ',a+1);body=s[a:b if b>=0 else len(s)].strip()
body=body.replace('trace_func_002ABB0C_r000AC70C','xr64_damage_reversal_activate',1)
body=body.replace('    // 0x002ABB50:', '    goto L_002ABD14; // Diagnostic: use native power-up initialization without a pickup object.\n    // 0x002ABB50:',1)
a=body.index('    // 0x002ABD70:');b=body.index('    // 0x002ABDAC:',a)
body=body[:a]+'''    ctx->r30 = ctx->r2 & 0X6000;
    ctx->r2 = 0x10; // Verified Damage Reversal selection; no RNG or pickup consumption.
'''+body[b:]
# Diagnostic has no pickup object: all pickup-tail exits restore registers directly.
body=body.replace('goto L_002AC4C8;', 'goto L_002AC568;')
header='''// Generated by scripts/instrument_damage_reversal.py; native initialization retained.
#include "recomp.h"
#include "funcs.h"
extern int xr64_damage_reversal_take_request(void);
extern void xr64_damage_reversal_observe(int state);
'''
helper='''
void xr64_damage_reversal_tick(uint8_t* rdram, recomp_context* ctx) {
    const uint32_t actor = (uint32_t)ctx->r16;
    if (actor < 0x80000000U || actor > 0x807FE800U) return;
    if (MEM_W(actor, 0X1450) != 0 || MEM_W(actor, 0X5DC) == 0) return;
    uint32_t flags = MEM_W(actor, 0X122C);
    if (xr64_damage_reversal_take_request()) {
        if (flags & 0x10) {
            // Native simulation expires the effect and clears associated state.
            MEM_W(0X1230, actor) = 0;
        } else if (MEM_W(actor, 0X5E4) > 0 && (flags & 0x9FFF) == 0 && MEM_W(actor, 0X11E4) == 0) {
            recomp_context local = *ctx;
            local.r4 = (int32_t)actor;
            local.r5 = 0;
            xr64_damage_reversal_activate(rdram, &local);
        } else {
            xr64_damage_reversal_observe(2); // Refused: dead or another effect owns the slot.
            return;
        }
    }
    xr64_damage_reversal_observe((MEM_W(actor, 0X122C) & 0x10) != 0);
}
'''
if args.generation_only:
 existing=(r/'staging/rage-wars-recomp-spike/generated/ares_boot_to_combat/funcs_19.c').read_text()
 if '#include "damage_reversal_diagnostic.inl"' not in existing or existing.count('xr64_damage_reversal_tick(rdram, ctx);')!=1:
  raise ValueError('Generation-only requires preserved guest integration')
 if 'SDLK_F10 && !event.key.repeat' not in (r/'xr64/games/rage_wars/recomp_host/src/rage_wars_desktop_renderer.cpp').read_text():
  raise ValueError('Generation-only requires preserved host integration')
out=r/'staging/rage-wars-recomp-spike/generated/ares_boot_to_combat/damage_reversal_diagnostic.inl';out.write_text(header+body+'\n'+helper)
if args.generation_only:
 print('Regenerated diagnostic input; host and guest integration unchanged')
 raise SystemExit(0)
p=r/'staging/rage-wars-recomp-spike/generated/ares_boot_to_combat/funcs_19.c';s=p.read_text();
if '#include "damage_reversal_diagnostic.inl"' in s:
 assert s.count('xr64_damage_reversal_tick(rdram, ctx);')==1
 assert 'SDLK_F10 && !event.key.repeat' in (r/'xr64/games/rage_wars/recomp_host/src/rage_wars_desktop_renderer.cpp').read_text()
 print('Regenerated diagnostic; existing hooks verified')
 raise SystemExit(0)
s=s.replace('extern int xr64_rw092_ai_freeze_enabled(void);','extern int xr64_rw092_ai_freeze_enabled(void);\n#include "damage_reversal_diagnostic.inl"',1);s=s.replace('    // RW092 AI SIMULATION GATE:', '    xr64_damage_reversal_tick(rdram, ctx);\n    // RW092 AI SIMULATION GATE:',1);p.write_text(s)
p=r/'xr64/games/rage_wars/recomp_host/src/rage_wars_desktop_renderer.cpp';s=p.read_text();anchor='static std::atomic<bool> rw092_ai_freeze{false};';block='''static std::atomic<bool> reversal_request{false};
static std::atomic<int> reversal_state{0};
extern "C" int xr64_damage_reversal_take_request() {
    return reversal_request.exchange(false, std::memory_order_relaxed) ? 1 : 0;
}
extern "C" void xr64_damage_reversal_observe(int state) {
    const int old = reversal_state.exchange(state, std::memory_order_relaxed);
    if (old != state) std::fprintf(stderr, "RW095_DAMAGE_REVERSAL state=%d (0=off,1=on,2=refused)\\n", state);
}
''';s=s.replace(anchor,block+anchor,1)
anchor='            if (event.key.keysym.sym == SDLK_F4) {'
s=s.replace(anchor,'''            if (event.key.keysym.sym == SDLK_F10 && !event.key.repeat) {
                reversal_request.store(true, std::memory_order_relaxed);
                std::fprintf(stderr, "RW095_DAMAGE_REVERSAL toggle_requested=1\\n");
            }
'''+anchor,1)
needle='(xr64_rw092_ai_freeze_enabled()?" | AI FREEZE ON":" | AI FREEZE OFF")';s=s.replace(needle,needle+' + (reversal_request.load()?" | F10 REV PENDING":reversal_state.load()==1?" | F10 REV ON":reversal_state.load()==2?" | F10 REV BLOCKED":" | F10 REV OFF")',1);p.write_text(s)
