#!/usr/bin/env python3
"""Regenerate private audio C++ from a pinned ROM; optionally diagnose a snapshot."""
from pathlib import Path
import argparse
import hashlib
import json
import struct
import subprocess


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def require(condition, message):
    if not condition:
        raise ValueError(message)


def verify_rom(rom, manifest):
    require(sha256(rom) == manifest["rom_sha256"], "ROM SHA-256 mismatch")
    regions = {}
    for kind in ("text", "data"):
        start = manifest[kind + "_rom"]
        size = manifest[kind + "_size"]
        require(0 <= start and 0 < size and start + size <= len(rom),
                kind + " region is outside the ROM")
        region = rom[start:start + size]
        require(sha256(region) == manifest[kind + "_sha256"],
                kind + " region SHA-256 mismatch")
        regions[kind] = region
    table_offset = manifest["handler_table_offset"]
    require(0 <= table_offset and table_offset + 32 <= len(regions["data"]),
            "Handler table is outside the audio data region")
    targets = list(struct.unpack_from(">16H", regions["data"], table_offset))
    require(targets == manifest["handler_targets"], "Handler table mismatch")
    require(all(manifest["text_rsp"] <= target <
                manifest["text_rsp"] + manifest["text_size"] and target % 4 == 0
                for target in targets), "Invalid audio handler target")
    return regions


def verify_snapshot(snapshot, regions, manifest):
    require(sha256(snapshot) == manifest["snapshot_sha256"],
            "Diagnostic snapshot SHA-256 mismatch")
    for kind, region in regions.items():
        start = manifest[kind + "_guest"] & 0x1FFFFFFF
        indices = [(start + index) ^ 3 for index in range(len(region))]
        require(all(index < len(snapshot) for index in indices),
                kind + " region is outside the diagnostic snapshot")
        require(region == bytes(snapshot[index] for index in indices),
                kind + " ROM/snapshot comparison mismatch")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--generator", type=Path, required=True)
    parser.add_argument("--work", type=Path, required=True)
    parser.add_argument("--snapshot", type=Path,
                        help="Optional pinned RAM snapshot diagnostic; never required for generation")
    parser.add_argument("--compare", type=Path,
                        help="Compare generated bytes with an existing file without replacing it")
    args = parser.parse_args()
    manifest = json.loads(Path(__file__).with_name("audio_rsp_manifest.json").read_text(encoding="utf-8"))
    rom = args.rom.read_bytes()
    regions = verify_rom(rom, manifest)
    generator_hash = sha256(args.generator.read_bytes())
    require(generator_hash == manifest["generator_sha256"], "RSP generator SHA-256 mismatch")
    snapshot_check = "not_requested"
    if args.snapshot is not None:
        verify_snapshot(args.snapshot.read_bytes(), regions, manifest)
        snapshot_check = "passed"
    work = args.work.resolve()
    output = work / "rage_wars_audio_ucode.cpp"
    comparison_bytes = None
    if args.compare is not None:
        require(args.compare.resolve() != output,
                "Comparison file must be outside the regeneration output path")
        comparison_bytes = args.compare.read_bytes()
    work.mkdir(parents=True, exist_ok=True)
    config = (
        "text_offset = " + str(manifest["text_rom"]) + "\n"
        "text_size = " + str(manifest["text_size"]) + "\n"
        "text_address = " + str(manifest["text_rsp"]) + "\n"
        "rom_file_path = " + json.dumps(args.rom.resolve().as_posix()) + "\n"
        "output_file_path = \"rage_wars_audio_ucode.cpp\"\n"
        "output_function_name = \"rage_wars_audio_ucode\"\n"
        "extra_indirect_branch_targets = " + json.dumps(manifest["handler_targets"]) + "\n"
    )
    config_path = work / "audio.toml"
    config_path.write_text(config, encoding="utf-8")
    result = subprocess.run([str(args.generator.resolve()), str(config_path)],
                            cwd=work, capture_output=True, text=True, check=True)
    require("Unhandled instruction" not in result.stdout + result.stderr,
            "RSP generator reported an unhandled instruction")
    generated = output.read_bytes()
    require(b"# INVALID" not in generated, "Generated audio C++ contains an invalid instruction")
    evidence = {
        "rom_sha256": sha256(rom),
        "text_sha256": sha256(regions["text"]),
        "data_sha256": sha256(regions["data"]),
        "generator_sha256": generator_hash,
        "snapshot_comparison": snapshot_check,
        "generated_sha256": sha256(generated),
        "runtime_acceptance": "pending",
    }
    if comparison_bytes is not None:
        evidence["comparison"] = {
            "existing_sha256": sha256(comparison_bytes),
            "byte_identical": generated == comparison_bytes,
        }
        require(args.compare.read_bytes() == comparison_bytes,
                "Existing comparison file changed during regeneration")
    (work / "evidence.json").write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    print("Verified audio ROM, regions, handler table and RSP generation; snapshot: " + snapshot_check)
    if comparison_bytes is not None:
        print("Existing audio C++ comparison: " +
              ("byte-identical" if generated == comparison_bytes else "DIFFERENT; no replacement performed"))
        return 0 if generated == comparison_bytes else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
